### ISSUE TITLE
Performance testing using Blaze Meter RTE Plug in for Mico focus Reflection Application.

### ISSUE THREAD

**Issue by Rnandiraju** [Blazemeter/RTEPlugin#28]
Hello,

I have been trying to use the RTE plugin in Jmeter to test Micro focus Reflection application. 

When I Try to connect using the recorder it gives the bellow error. 
2022-04-20 08:54:03,292 ERROR o.a.j.JMeter: Uncaught exception in thread Thread[Thread-9,5,main]

java.security.InvalidParameterException: Unknown telnet command type: FD 27

 

              at com.bytezone.dm3270.telnet.TelnetCommand.<init>(TelnetCommand.java:82) ~[dm3270-lib-0.14.jar:?]

              at com.bytezone.dm3270.streams.TelnetListener.processTelnetCommand(TelnetListener.java:146) ~[dm3270-lib-0.14.jar:?]

              at com.bytezone.dm3270.telnet.TelnetProcessor.listen(TelnetProcessor.java:105) ~[dm3270-lib-0.14.jar:?]

              at com.bytezone.dm3270.streams.TelnetListener.listen(TelnetListener.java:58) ~[dm3270-lib-0.14.jar:?]

              at com.bytezone.dm3270.streams.TerminalServer.run(TerminalServer.java:71) ~[dm3270-lib-0.14.jar:?]

              at java.lang.Thread.run(Unknown Source) [?:1.8.0_321]

If any one have experienced the similar kind of issue.  Can you please advise.

**Comment by RicardoPoleo** [comment]
Hello @Rnandiraju,

Thanks for taking the time to report this behaviour, we really appreciate it. 

Some users have experienced issues with unsupported telnet commands while using our plugin. We found that this particular [workaround](https://github.com/Blazemeter/dm3270/pull/17) worked for some of them (but none provided flows for us to try to fix it more accordingly).

In order to help you, could you:
1. Share with me a TestPlan/JTL so we can reproduce your scenario and fix it?
2. Try that proposed workaround and let us know if that works in your case?

The 1st option would also help the community, thus, we could mention you as scenario collaborators
The 2nd option would also prove another case where this is the correct approach (and such, we could implement it on our end).

Regardless of the option you pick, please let me know either here or in my email (ricardo.poleo@blazemeter.com) and, as always:

Happy Hacking!

**Comment by Rnandiraju** [comment]
Hello Ricardo Poleo,

The work around suggested did not work.

Any other options?

Rajasri

**Comment by Rnandiraju** [comment]
Does RTE Plug in support Micro focus reflection or we need to use any other plug in Please suggest.
