### ISSUE TITLE
Error : Screen not composed by fields. None found

### ISSUE THREAD

**Issue by andisetiandi** [Blazemeter/RTEPlugin#32]
hi all,

i have issues when i'm using bzm-rte.. 
i have succesfully login.. but in one page have errors after im entering 2 fields (policy number and option)
error shows popup message : "Screen not composed by fields. None found."
i'm using jmeter 5.4.3 and bzm-rte 3.2.2

[jmeter_rte_screen-not-composed-by-fields.docx](https://github.com/Blazemeter/RTEPlugin/files/10038856/jmeter_rte_screen-not-composed-by-fields.docx)

pls help.. thank you

regards
andi

**Comment by danielgoodwin** [comment]
Same issue . bzm-rte 3.2.2. Happens on an F4 prompt - which opens window. Using xtn5250 directly - no issue with emulation. 
Stack below

`2023/02/16 12:16:09 ERROR - com.blazemeter.jmeter.rte.recorder.RTERecorder: Screen not composed by fields. None found. com.blazemeter.jmeter.rte.core.exceptions.ScreenWithoutFieldException: Screen not composed by fields. None found.
	at com.blazemeter.jmeter.rte.protocols.tn5250.Tn5250Client.setFieldByNavigationType(Tn5250Client.java:189)
	at com.blazemeter.jmeter.rte.protocols.tn5250.Tn5250Client.setField(Tn5250Client.java:156)
	at com.blazemeter.jmeter.rte.core.BaseProtocolClient.lambda$send$1(BaseProtocolClient.java:46)
	at com.blazemeter.jmeter.rte.core.BaseProtocolClient$$Lambda$89/1778903551.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at com.blazemeter.jmeter.rte.core.BaseProtocolClient.send(BaseProtocolClient.java:46)
	at com.blazemeter.jmeter.rte.recorder.RTERecorder.onAttentionKey(RTERecorder.java:415)
	at com.blazemeter.jmeter.rte.recorder.emulator.XI5250CrtBase.processAttentionKey(XI5250CrtBase.java:125)
	at com.blazemeter.jmeter.rte.recorder.emulator.XI5250CrtBase.processKeyEvent(XI5250CrtBase.java:96)
	at java.awt.Component.processEvent(Component.java:6302)
	at java.awt.Container.processEvent(Container.java:2234)
	at java.awt.Component.dispatchEventImpl(Component.java:4881)
	at java.awt.Container.dispatchEventImpl(Container.java:2292)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1954)
	at java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:806)
	at java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1074)
	at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:945)
	at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:771)
	at java.awt.Component.dispatchEventImpl(Component.java:4752)
	at java.awt.Container.dispatchEventImpl(Container.java:2292)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:751)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:702)
	at java.awt.EventQueue$3.run(EventQueue.java:696)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:721)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)`

**Comment by danielgoodwin** [comment]
Additional information. I reverted the plugin to version 2.3 and used xtn5250-3.2.jar (from Version 2.3 assets) . This corrected the issue for me.
