### ISSUE TITLE
Unable to record - TN3270 protocol with Apache Jmeter 5.6.2 or 5.6.3 - java.security.InvalidParameterException: Unknown telnet command type: FD 27

### ISSUE THREAD

**Issue by amitharangi** [Blazemeter/RTEPlugin#40]
The following jars were used
dm3270-lib-0.15
jmeter-bzm-rte-3.2.2 and 3.3
jVT220-1.3.2
xtn5250-3.2.4

2024-10-21 14:28:41,279 DEBUG o.a.j.g.GuiPackage: Gui retrieved = org.apache.jmeter.visualizers.ViewResultsFullVisualizer[View Results Tree,0,0,1440x533,invalid,layout=java.awt.BorderLayout,alignmentX=0.0,alignmentY=0.0,border=javax.swing.border.EmptyBorder@2d25cc4b,flags=9,maximumSize=,minimumSize=,preferredSize=]
2024-10-21 14:28:41,279 DEBUG o.a.j.g.GuiPackage: Gui retrieved = org.apache.jmeter.visualizers.ViewResultsFullVisualizer[View Results Tree,0,0,1440x533,invalid,layout=java.awt.BorderLayout,alignmentX=0.0,alignmentY=0.0,border=javax.swing.border.EmptyBorder@61a60d83,flags=9,maximumSize=,minimumSize=,preferredSize=]
2024-10-21 14:28:57,716 DEBUG o.a.t.p.n.NamedEntityParser: WhenStartIsPressed
2024-10-21 14:28:57,716 DEBUG o.a.j.g.AbstractJMeterGuiComponent: setting element to enabled: true
2024-10-21 14:28:57,716 DEBUG c.b.j.r.r.RTERecorder: Start recording
2024-10-21 14:28:57,716 DEBUG o.a.j.g.GuiPackage: Updating current node bzm - RTE Recorder
2024-10-21 14:28:57,716 DEBUG o.a.j.g.GuiPackage: Gui retrieved = com.blazemeter.jmeter.rte.recorder.RTERecorderGui[bzm - RTE Recorder,0,0,1457x511,invalid,layout=java.awt.BorderLayout,alignmentX=0.0,alignmentY=0.0,border=javax.swing.border.EmptyBorder@4515892b,flags=9,maximumSize=,minimumSize=,preferredSize=]
2024-10-21 14:28:57,716 DEBUG o.a.j.g.AbstractJMeterGuiComponent: setting element to enabled: true
2024-10-21 14:28:57,716 DEBUG o.a.j.g.GuiPackage: Gui retrieved = com.blazemeter.jmeter.rte.sampler.gui.RTEConfigGui[bzm-RTE-config,0,0,1440x372,invalid,layout=java.awt.BorderLayout,alignmentX=0.0,alignmentY=0.0,border=javax.swing.border.EmptyBorder@1f2a954b,flags=9,maximumSize=,minimumSize=,preferredSize=]
2024-10-21 14:28:57,716 DEBUG o.a.j.g.AbstractJMeterGuiComponent: setting element to enabled: true
2024-10-21 14:28:57,716 DEBUG o.a.j.g.GuiPackage: Gui retrieved = com.blazemeter.jmeter.rte.recorder.RTERecorderGui[bzm - RTE Recorder,0,0,1457x511,invalid,layout=java.awt.BorderLayout,alignmentX=0.0,alignmentY=0.0,border=javax.swing.border.EmptyBorder@4515892b,flags=9,maximumSize=,minimumSize=,preferredSize=]
2024-10-21 14:28:57,716 DEBUG o.a.j.g.GuiPackage: Updating gui to new node
2024-10-21 14:28:57,716 DEBUG c.b.d.s.TelnetState: setting: IBM-3278-2
2024-10-21 14:28:57,716 DEBUG c.b.d.s.TelnetState: setting: IBM-3278-2
2024-10-21 14:28:57,731 DEBUG o.a.j.u.CustomX509TrustManager:  Server certificate 1:
  Subject DN: CN=WLF1N1DAZ1MFS02.wlife.com.au, OU=IT, O=Reslife Services, L=sydney, ST=NSW, C=AU
  Signature Algorithm: SHA256withRSA
  Valid from: 2024-07-15T15:24:10.000+1000
  Valid until: 2026-07-15T15:24:10.000+1000
  Issuer: CN=wLifeSubCA01, DC=wlife, DC=com, DC=au
2024-10-21 14:28:57,747 ERROR o.a.j.JMeter: Uncaught exception in thread Thread[Thread-25,5,main]
java.security.InvalidParameterException: Unknown telnet command type: FD 27

	at com.bytezone.dm3270.telnet.TelnetCommand.<init>(TelnetCommand.java:82) ~[dm3270-lib-0.15.jar:?]
	at com.bytezone.dm3270.streams.TelnetListener.processTelnetCommand(TelnetListener.java:146) ~[dm3270-lib-0.15.jar:?]
	at com.bytezone.dm3270.telnet.TelnetProcessor.listen(TelnetProcessor.java:105) ~[dm3270-lib-0.15.jar:?]
	at com.bytezone.dm3270.streams.TelnetListener.listen(TelnetListener.java:58) ~[dm3270-lib-0.15.jar:?]
	at com.bytezone.dm3270.streams.TerminalServer.run(TerminalServer.java:71) ~[dm3270-lib-0.15.jar:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]

**Comment by RichB-2024** [comment]
I hit a similar problem just trying to run a test. I had upgraded the blazemeter RTE plugin from 3.2.2 to 3.3.  The "FD 27" is the beginning of 3270 terminal negotiation, sent by the cics region to jmeter. Jmeter should understand it and respond. Looking at the exception you can see that the problem is occurring in dm3270. These 2 version of the blazemeter RTE plugin both contain a jar called dm3270-lib-0.15.jar, but the jar is slightly different!  The contents (do a jar tvf) of the one that was part of 3.2.2 are from Oct26 2022. The contents of the one that came with 3.3 are from Oct 04 2021 ! 
So, to workaround the problem get the 3.2.2 version of that jar and put it in your jmeter/lib/ext directory. It got rid of the problem for me and it might work for you too.
